## Customised version of https://github.com/haroldelopez/ms-teams-notification-action/tree/master
name: 'MS Teams Notification Action'
description: 'Send a notification to Microsoft Teams for various events including pull requests and deployments'
inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Notification title'
    required: true
  message:
    description: 'Main notification message'
    required: true
  url:
    description: 'URL to link in the notification'
    required: false
    default: ''
  repo_name:
    description: 'Repository name'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Send Teams Notification
      shell: bash
      env:
        TEAMS_WEBHOOK_URL: ${{ inputs.webhook_url }}
        TITLE: ${{ inputs.title }}
        MESSAGE: ${{ inputs.message }}
        URL: ${{ inputs.url }}
        REPO_NAME: ${{ inputs.repo_name }}
      run: |
        # Function to check if a variable is empty
        is_empty() {
          local var_name="$1"
          local var_value="${!var_name}"
          if [ -z "$var_value" ]; then
            echo "Error: $var_name is required but not set."
            return 0
          fi
          return 1
        }

        # Check all required inputs
        required_inputs=("TEAMS_WEBHOOK_URL" "TITLE" "MESSAGE" "URL" "REPO_NAME")
        error_occurred=false

        for input in "${required_inputs[@]}"; do
          if is_empty "$input"; then
            error_occurred=true
          fi
        done

        if [ "$error_occurred" = true ]; then
          echo "One or more required inputs are missing. Please check the action configuration."
          exit 1
        fi

        # Set default values for optional inputs
        IMAGE="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

        # Escape special characters in variables
        escape_string() {
          echo "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/`/\\`/g; s/\$/\\$/g'
        }

        TITLE_ESCAPED=$(escape_string "$TITLE")
        MESSAGE_ESCAPED=$(escape_string "$MESSAGE")
        REPO_NAME_ESCAPED=$(escape_string "$REPO_NAME")
        URL_ESCAPED=$(escape_string "$URL")

        # Build the facts array dynamically
        FACTS=$( cat <<EOF
        [
          {"title": "Repository", "value": "$REPO_NAME_ESCAPED"},
          {"title": "Details", "value": "$MESSAGE_ESCAPED"},
          {"title": "Workflow run", "value": "<$URL_ESCAPED>"}
        ]
        EOF
        )

        # Send the notification
        PAYLOAD=$(cat <<EOF
        {
            "type": "AdaptiveCard",
            "\$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.5",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "View Workflow run",
                    "iconUrl": "$IMAGE",
                    "url": "$URL_ESCAPED"
                }
            ],
            "body": [
                {
                    "type": "TextBlock",
                    "style": "heading",
                    "text": "$TITLE_ESCAPED"
                },
                {
                    "type": "FactSet",
                    "facts": $FACTS
                }
            ]
        }
        EOF
        )
        curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"

        if [ $? -ne 0 ]; then
          echo "Failed to send notification to Microsoft Teams."
          exit 1
        else
          echo "Notification sent successfully to Microsoft Teams."
        fi
